# Generated by Django 3.2.6 on 2021-10-01 07:00

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='./', validators=[main.validators.file_size]),
        ),
    ]
