# Generated by Django 3.2.6 on 2021-10-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_video_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='caption',
        ),
    ]
